name: intelligrade
description: An intelligent grading system
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.0.0
  # path_provider: ^2.0.11

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_quill: ^10.5.14
  editable: ^2.0.0

  # Networking & API
  http: ^1.2.1
  dio: ^5.5.0+1

  # File & Media Handling
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  pdf: ^3.11.0

  # Data Management & Storage
  shared_preferences: ^2.2.3
  collection: ^1.18.0

  # Server & Routing
  shelf_router: ^1.1.4

  # Configuration & Environment
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0

  # Date & Time
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1  # Added for better code quality

flutter:
  uses-material-design: true
  
  assets:
    - assets/.env
